version: '3.9'

services:  
        
  springboot:
    image: challenge
    container_name: springboot    
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
