CREATE OR REPLACE TABLE PRODUCT (ID NUMBER PRIMARY KEY NOT NULL, NAME varchar(200) NOT NULL, DESCRIPTION VARCHAR(200) NOT NULL, PRICE decimal(6,2) NOT NULL);

CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1;